sudo: false
language: node_js
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ac517c45b9f9b45a77d2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - "tests/run_ci.sh"
